config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  resources :tasks
  # get 'tasks', to: 'tasks#index'
  # get 'tasks/:id', to: 'tasks#show', as: 'task_show'

  # get 'tasks/new', to: 'tasks#new'
  # post 'tasks', to: 'tasks#create'

  # get 'tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'
  # patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing <%= @task.title %></h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="container mt-5">
  <h1>List of all Tasks</h1>

  <table class="table">
    <tr>
      <th>Done ?</th>
      <th>Tasks</th>
      <th>Delete ?</th>
    </tr>

    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.completed? ? "✅" : "❌" %></td>
      <td><%= link_to "#{task.title}", tasks_path(task) %></td>
      <td><%= link_to "🗑", destroy_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } %></td>
      <% end %>
    </tr>
  </table>

<%= link_to "Add new Task", new_task_path, class: 'btn btn-primary' %>
</div>

app/views/tasks/new.html.erb
<div class="container mt-5">
<h1>Create new task</h1>

<%= render 'form' %>
</div>

app/views/tasks/show.html.erb
<div class="container mt-5">
  <h1> <%=  @task.title%></h1>
  <p><%= @task.details%></p>
  <p><%= @task.completed? ? "✅ this task is completed" : "❌ this task is not completed yet" %></p>
  <p><%= link_to "Edit task", edit_task_path(@task), class: 'btn btn-primary' %></p>
  <p><%= link_to "Back", tasks_path, class: 'btn btn-primary' %></p>
</div>